[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pycomm3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []


[tool.ruff]
line-length = 120

[dependency-groups]
dev = [
    'ruff',
    'hatchling',
    "pyright",
]
test = [
    'pytest',
    'pytest-pretty',
    'pytest-mock',
]
