__author__ = 'agostino'

from pycomm.ab_comm.slc import Driver as SlcDriver

if __name__ == '__main__':
    c = SlcDriver(True, 'delete_slc.log')
    if c.open('172.16.2.160'):
        print c.read_tag('S:1/5')
        print c.read_tag('S:60', 2)
        print c.read_tag('O:0.0', 6)
        print c.read_tag('O:0.0/4')
        print c.read_tag('B3:1/12')
        print c.read_tag('B3:100', 2)
        print c.read_tag('B3/3955')
        print c.read_tag('N7:0/2')
        print c.read_tag('N7:0', 6)
        print c.read_tag('F8:0', 3)
        print c.read_tag('T4:0.PRE')
        print c.read_tag('T4:0.ACC')
        print c.read_tag('T4:0.EN')
        print c.read_tag('T4:0.TT')
        print c.read_tag('T4:0.DN')
        print c.read_tag('C5:0.PRE')
        print c.read_tag('C5:0.ACC')
        #print c.read_tag('C5:0.CU')
        #print c.read_tag('C5:0.CD')
        #print c.read_tag('C5:0.DN')
        #print c.read_tag('C5:0.OV')
        #print c.read_tag('C5:0.UN')
        #print c.read_tag('C5:0.UA')
        #print c.write_tag('N7:0', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
        #print c.write_tag('F8:1', 3.0)
        #print c.write_tag('T4:2.PRE', 1000)
        #print c.write_tag('B3:0', 12)
        #print c.read_tag('N7:0', 10)
        #print c.read_tag('B3:0')
        #print c.read_tag('F8:0', 2)
        #print c.read_tag('T4:2.PRE')
    c.close()
